version: 0.2
phases:
  install:
    commands:
      - curl -O https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
      - unzip packer_1.7.5_linux_amd64.zip
  build:
    commands:
      - ./packer build windows-ami.pkr.hcl